environment: development

apphost: k8s

kubehelmapi:
  label:
    name: aspnet3core

  container:
    name: aspnet3
    pullPolicy: IfNotPresent
    image: deathstroke45/shoppingapi
    tag: latest
    port: 80
  replicas: 1

  service:
    port: 8888
    type: NodePort