apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hemlapi-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1 
spec:
  tls:
    - hosts:
        - somednsname #dns mapped with ip
      secretName: hello-certs
  rules:
   - http:
      paths: 
      - path: /?(.*)
        backend:
          serviceName: {{ .Release.Name }}-service
          servicePort: {{ .Values.kubehelmapi.service.port }}